#!/bin/bash

. .adb

function usage()
{
    echo "Usage: $0 [url]"
    exit
}

url=$1
regex='(https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'

if [[ $url =~ $regex ]]; then
    intent VIEW "$url"
else
    usage
fi
