#!/bin/bash

. .adb

while [ true ]; do
    $adb wait-for-device
    level=$($adb shell dumpsys battery | grep "^[\ ]*level:\ [0-9]\+" | awk '{print $2}')
    level=${level%?}
    echo -ne "\rBattery: ${level}%"
    sleep 15s
done
